### ISSUE TITLE
Implement monitoring feature on Parser app

### ISSUE THREAD

**Issue by dasBikash84** [dasBikash84/ns_reloaded_backend_Parser_#24]
### Tasks:

- [x] Generate daily parsing report in excel format.
- [x] Generate weekly parsing report in excel format.
- [x] Generate monthly parsing report in excel format.
- [x] Notify admin if not new article is downloaded for any NP in whole day.
- [x] Notify admin if not new article is downloaded for any page in whole week.
